[default]
fuzz_runs = 1024
libs = ['node_modules']
optimizer = true
optimizer_runs = 200
out = 'out'
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'hardhat/=node_modules/hardhat/',
]
src = 'contracts'
test = 'test'
gas_reports = ["*"]
