# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:


jobs:
  nodeJob:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: sudo curl -N -L "https://github.com/gakonst/foundry/releases/download/nightly-d08a59ec16e07329c70f9a5ccf5dbb92baf367f3/foundry_nightly_linux_amd64.tar.gz" | sudo tar xvz -C /bin
      - run: npm install --global yarn && yarn
      - run: yarn format-lint
      - run: yarn build
      - run: yarn test