# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:


jobs:
  nodeJob:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: sudo curl -L https://github.com/gakonst/foundry/releases/download/nightly-31e4a9d3a3f33e1865a2d1169a0538bc96eee797/foundry_nightly_linux_amd64.tar.gz | sudo tar zxv -C /bin
      - run: npm install --global yarn && yarn
      - run: yarn format-lint
      - run: yarn build
      - run: ls
      - run: yarn test
  go_test_job:
    needs: nodeJob
    runs-on: ubuntu-18.04
    env:
      GOPRIVATE: github.com/ontology-layer-2
      GH_ACCESS_TOKEN: ${{ secrets.ROLLUP_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Inject insteadOf configuration for l2 private repo
        run: |
          git config --global url."https://${{ secrets.ROLLUP_ACCESS_TOKEN }}:x-oauth-basic@github.com/ontology-layer-2".insteadOf "https://github.com/ontology-layer-2"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: ls
      - name: command
        run: bash ./.github/workflows/.gha.precheck.sh


