# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install prerequisites
      shell: bash
      run: sudo apt-get -y update ; sudo apt-get -y install gcc-arm-linux-gnueabihf
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Show installed version information (Rust, cargo, GCC,...)
      shell: bash
      run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V
    - run: wget -c https://github.com/gakonst/foundry/releases/download/nightly-31e4a9d3a3f33e1865a2d1169a0538bc96eee797/foundry_nightly_linux_amd64.tar.gz -o - | tar -xvf
    - run: npm install --global yarn && yarn
    - run: yarn format-lint
    - run: yarn build
    - run: yarn test
