on:
  pull_request:
    branches:
    # - master


jobs:

  build:
    runs-on: ubuntu-18.04
    env:
      GOPRIVATE: github.com/ontology-layer-2
      GH_ACCESS_TOKEN: ${{ secrets.ROLLUP_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Inject insteadOf configuration for l2 private repo
        run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: command
        run: bash ./.gha.precheck.sh
